CREATE TABLE `tb_apply_info_%s` (
  `apply_info_id` varchar(50) NOT NULL,
  `user_id` varchar(50) DEFAULT NULL,
  `product_id` int(11) DEFAULT NULL,
  `partner_id` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `mobile` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `advertisement_amount` int(11) DEFAULT NULL,
  `repay_days` int(11) DEFAULT NULL,
  `repay_months` int(11) DEFAULT NULL,
  `month_repay_date` int(11) DEFAULT NULL,
  `month_repay_amount` decimal(20,2) DEFAULT NULL,
  `poundage` decimal(20,2) DEFAULT NULL,
  `month_rate` decimal(20,2) DEFAULT NULL,
  `month_service_rate` decimal(20,2) DEFAULT NULL,
  `first_repay_date` timestamp NULL DEFAULT NULL,
  `real_repay_date` timestamp NULL DEFAULT NULL,
  `real_repay_amount` decimal(20,2) DEFAULT NULL,
  `overdue_amount` decimal(20,2) DEFAULT NULL,
  `user_ip` varchar(255) DEFAULT NULL,
  `user_agent` text,
  `status` int(8) DEFAULT NULL,
  `partner_status` int(8) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`apply_info_id`),
  UNIQUE KEY `unique` (`product_id`,`mobile`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;